### ISSUE TITLE
Opens a terminal window but doesn't run anything

### ISSUE THREAD

**Issue by mrjones2014** [neoclide/coc-jest#19]
With the configuration from the README.md: 

```
" Run jest for current project
command! -nargs=0 Jest :call  CocAction('runCommand', 'jest.projectTest')

" Run jest for current file
command! -nargs=0 JestCurrent :call  CocAction('runCommand', 'jest.fileTest', ['%'])

" Run jest for current test
nnoremap <leader>te :call CocAction('runCommand', 'jest.singleTest')<CR>

" Init jest in current cwd, require global jest command exists
command! JestInit :call CocAction('runCommand', 'jest.init')
```

the commands open a new terminal window, but don't actually run anything in it.

You can see in the status line, it shows the command that is _supposed_ to be running, but nothing actually runs. 
![Screen Shot 2021-05-19 at 1 24 13 PM](https://user-images.githubusercontent.com/8648891/118857074-a3135580-b8a5-11eb-9101-d5b719dca851.png)

**Comment by sushovan-mryum** [comment]
Something to do with [watchman](https://github.com/facebook/draft-js/issues/2183) ?

**Comment by chemzqm** [comment]
Don't know, could be issue with your jest and project configuration

**Comment by mrjones2014** [comment]
I've long since switched to Neovim LSP anyway. We can close this.
