### ISSUE TITLE
I don't see any highlighting of failed tests. 

### ISSUE THREAD

**Issue by vitaly** [neoclide/coc-jest#21]
The tests run in a terminal window. and I see the failure there, but nothing is changed in the source window.
I tried to look through the source, but I couldn't find any code dealing with this... any pointers wold be appreciated.

**Comment by chemzqm** [comment]
No such kind of support yet, it was planned before.

**Comment by vitaly** [comment]
Well, in this case it shouldn't "advertise" it on the Readme ;)
