### ISSUE TITLE
`findTestName` errors if test name has special characters

### ISSUE THREAD

**Issue by timhwang21** [neoclide/coc-jest#22]
Repro: name a test like `it('does stuff [foobar]', () => {})`.  This will cause Jest to have an error `Invalid regular expression: /your test title/: Range out of order in character class`. This is because Jest's `-t` flag [treats the string as a regexp](https://jestjs.io/docs/cli#--testnamepatternregex).

It seems [this line](https://github.com/neoclide/coc-jest/blob/4495f5f52e5a852598874c3d60eeedea60e4b986/src/index.ts#L48) attempts to fix this, but it would be more comprehensive to use something like [escape-string-regexp](https://github.com/sindresorhus/escape-string-regexp/blob/main/index.js). This single-function library is small enough to just be vendored in to keep this package dependency free.

I can file a PR if desired!

**Comment by chemzqm** [comment]
PR welcome
